[project]
name = "comfyui-mdsnodes"
description = "Custom Nodes for The Ultimate Model Tester Workflow"
version = "1.1.1"
license = { file = "LICENSE" }
dependencies  = []

[project.urls]
Repository = "https://github.com/MarwanDSAI/comfyui-mdsnodes"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "marwandsai"
DisplayName = "ComfyUI-MDSNodes"
Icon = "https://raw.githubusercontent.com/MarwanDSAI/comfyui-mdsnodes/main/images/logo.svg"
