[project]
name = "comfyui-mdsnodes"
version = "1.0.13"
description = "A collection of lightweight utility nodes for workflow automation and model routing."
authors = [{ name = "Marwan"}]
readme = "README.md"
license = { text = "MIT" }
dependencies = []
keywords = ["comfyui", "custom-nodes", "utilities"]

[project.urls]
Repository = "https://github.com/MarwanDSAI/comfyui-mdsnodes"
Homepage = "https://github.com/MarwanDSAI/comfyui-mdsnodes"


[tool.comfy]
PublisherId = "marwandsai"
DisplayName = "ComfyUI-MDSNodes"
Icon = "https://raw.githubusercontent.com/MarwanDSAI/comfyui-mdsnodes/main/images/logo.svg"

includes = [
    "**/*"
]
