# Marwan Custom Nodes
# Extracts a value from appended metadata based on a specific key. metadata structure Key1 [Value1]; Key2 [Value2]; Key3 [Value3];...
# -------------------------------------------------------
import re

class MarMetaDataExtract:
    DESCRIPTION = "Extracts a value from appended metadata based on a specific key. metadata structure Key1 [Value1]; Key2 [Value2]; Key3 [Value3];..."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                # Receives the string generated by MarMetaDataAppend
                "metadata": ("STRING", {
                    "default": "",
                    "forceInput": True,
                    "tooltip": "The metadata string to parse."
                }),
                # Text box for the user to specify which key to find
                "key": ("STRING", {
                    "default": "my_key",
                    "multiline": False,
                    "tooltip": "The exact key name to search for in the metadata."
                }),
            }
        }

    RETURN_TYPES = ("STRING", "BOOLEAN")
    RETURN_NAMES = ("value", "key_exists")
    OUTPUT_TOOLTIPS = ("The extracted value string.", "True if the key was found, False otherwise.")
    
    FUNCTION = "extract_data"
    CATEGORY = "MDSNodes/text"

    def extract_data(self, metadata=None, key=""):
        # Safely treat None or missing inputs as empty strings
        in_str = str(metadata) if metadata is not None else ""
        k_str = str(key).strip() if key is not None else ""

        # Return empty/False immediately if inputs are missing
        if not k_str or not in_str:
            return ("", False)

        # Regex pattern to match: optional semicolon/space, the key, optional space, and brackets
        # Example format matched: "; Key1 [Value1]" or "Key1 [Value1]"
        pattern = rf"(?:^|;\s*){re.escape(k_str)}\s*\[(.*?)\]"
        match = re.search(pattern, in_str)

        if match:
            # Group 1 contains the text captured inside the brackets
            return (match.group(1), True)
        
        return ("", False)