# Marwan Custom Nodes
# hecks if a specific key and value pair exists in the metadata string.metadata structure Key1 [Value1]; Key2 [Value2]; Key3 [Value3];...
# -------------------------------------------------------
import re

class MarMetaDataCheckKeyValue:
    DESCRIPTION = "Checks if a specific key and value pair exists in the metadata string."

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                # Receives the string generated by appending nodes
                "metadata": ("STRING", {
                    "default": "",
                    "forceInput": True,
                    "tooltip": "The metadata string to parse."
                }),
                # Text box for the user to specify which key to find
                "key": ("STRING", {
                    "default": "my_key",
                    "multiline": False,
                    "tooltip": "The exact key name to search for."
                }),
                # Text box for the user to specify the required value
                "value": ("STRING", {
                    "default": "my_value",
                    "multiline": False,
                    "tooltip": "The exact value to verify."
                }),
            }
        }

    RETURN_TYPES = ("BOOLEAN",)
    RETURN_NAMES = ("exists",)
    OUTPUT_TOOLTIPS = ("True if both the key and the exact value match, False otherwise.",)
    
    FUNCTION = "check_pair"
    CATEGORY = "MDSNodes/text"

    def check_pair(self, metadata=None, key="", value=""):
        # Safely treat None or missing inputs as empty strings
        in_str = str(metadata) if metadata is not None else ""
        k_str = str(key).strip() if key is not None else ""
        v_str = str(value).strip() if value is not None else ""

        # Return False immediately if key or metadata is missing
        if not k_str or not in_str:
            return (False,)

        # Regex pattern to match: optional semicolon/space, the key, optional space, and brackets
        pattern = rf"(?:^|;\s*){re.escape(k_str)}\s*\[(.*?)\]"
        match = re.search(pattern, in_str)

        if match:
            # Group 1 contains the text captured inside the brackets
            extracted_value = match.group(1).strip()
            # Verify if the extracted value matches the user's targeted value
            if extracted_value == v_str:
                return (True,)
        
        return (False,)